kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: k8s
networking:
  ipFamily: ipv4
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  # disableDefaultCNI: true
  kubeProxyMode: "ipvs"  # iptables and ipvs

nodes:
- role: control-plane
  extraMounts:
  - hostPath: /Users/sanehe/xiaoyinka
    containerPath: /www
  # extraPortMappings:
  #   - containerPort: 6444
  #     hostPort: 6444
  #     # optional: set the bind address on the host
  #     # 0.0.0.0 is the current default
  #     listenAddress: "127.0.0.1"
  #     # optional: set the protocol to one of TCP, UDP, SCTP.
  #     # TCP is the default
  #     protocol: TCP
# - role: control-plane
# - role: control-plane
# - role: worker
# - role: worker
# - role: worker


#########################################################################################################
# forbidden: User \"system:anonymous\" cannot get path \"/\"
# grep 'client-certificate-data' ~/.kube/config | head -n 1 | awk '{print $2}' | base64 -d >> kubecfg.crt
#
#
#########################################################################################################


#########################################################################################################
# dashboard
# kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml
# kubectl create clusterrolebinding default-admin --clusterrole cluster-admin --serviceaccount=default:default
#  第一种
# token=$(kubectl get secrets -o jsonpath="{.items[?(@.metadata.annotations['kubernetes\.io/service-account\.name']=='default')].data.token}"|base64 --decode)
# echo $token  echo $token > dashboard-token.txt
# 第二种
# kubectl get secrets
# kubectl describe secret default-token-2989r 
# https://127.0.0.1:6443/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/service?namespace=_all
#########################################################################################################
