version: '3'
services:
  webdav:
    image: bytemark/webdav
    restart: always
    ports:
      - "888:80"
    environment:
      AUTH_TYPE: Digest
      USERNAME: sane
      PASSWORD: sane
    volumes:
      - /data/apps/webdav/database:/var/lib/dav
